### ISSUE TITLE
Remove web app code

### ISSUE THREAD

**Issue by PrabhanshuAttri** [mercury-telemetry/mercury-hardware#7]
As this repository should contain code related to hardware, we should remove the bloated code from the repository

## Expected Behavior
The repository should contain source code related to the hardware only

## Current Behavior
The repository contains a web app source code as well.

## Ideas for Improvement
Purge web app code and reconfigure testing framework to work independently for hardware source code.

## Steps to Reproduce
1. Go to [https://github.com/mercury-telemetry/mercury-hardware](https://github.com/mercury-telemetry/mercury-hardware)

## Context (Environment)
Reducing the storage occupied by the repository on raspberry pis

**Comment by jackxujh** [comment]
Possibly a duplicate of #1 .
